using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Catalog.API.Entities
{
    public class Product
    {
        [BsonId]//set 'Id' as document id from mongoDB
        [BsonRepresentation(BsonType.ObjectId)]//this Id generated by mongodb
        public string Id { get; set; }

        [BsonElement("Name")]//used to change column name
        public string Name { get; set; }
        public string Category { get; set; }
        public string Summary { get; set; }
        public string Description { get; set; }
        public string ImageFile { get; set; }
        public decimal Price { get; set; }
    }
}
